In [1]:
import pandas as pd

df = pd.read_excel("../plan_de_compras_2025.xlsx")

print("Archivo cargado correctamente")
print("Filas y columnas:", df.shape)

Archivo cargado correctamente
Filas y columnas: (831, 26)

In [2]:
resumen_tipo_proyecto = df.groupby("Tipo Proyecto").agg(
    Cantidad_Registros=("ID Proyecto", "count"),
    Monto_Total=("Monto Total Ítem Año 2025", "sum")
).reset_index()

resumen_tipo_proyecto

          Tipo Proyecto  Cantidad_Registros  Monto_Total
0  Proyecto estratégico                 218   7195631224
1  Proyecto operacional                 613  77138651126

In [3]:
resumen_estado = df.groupby("Estado Proyecto").agg(
    Cantidad_Registros=("ID Proyecto", "count"),
    Monto_Total=("Monto Total Ítem Año 2025", "sum")
).reset_index()

resumen_estado

  Estado Proyecto  Cantidad_Registros  Monto_Total
0     Actualizado                 648  79232141166
1       Publicado                 183   5102141184

In [4]:
resumen_unidad = df.groupby("Unidad de Compra").agg(
    Cantidad_Registros=("ID Proyecto", "count"),
    Monto_Total=("Monto Total Ítem Año 2025", "sum")
).reset_index()

resumen_unidad = resumen_unidad.sort_values(
    "Monto_Total",
    ascending=False
)

resumen_unidad

                           Unidad de Compra  Cantidad_Registros  Monto_Total
0   Ministerio de Vivienda y Urbanismo(766)                 684  81943911910
8                     SEREMI MINVU V REGION                  30   1187465518
5                   SEREMI MINVU III REGION                  25    309240000
14       SERVICIO DE BIENESTAR MINVU SERVIU                   4    248000000
9                    SEREMI MINVU VI REGION                  20    162228246
6    SEREMI MINVU REGION ARICA Y PARINACOTA                   9    135080000
4                    SEREMI MINVU II REGION                   8    112600006
12                       SEREMI VIII REGION                   6    109333336
7                           SEREMI MINVU RM                   3     37427780
11                   SEREMI MINVU XI REGION                   8     19992000
10                  SEREMI MINVU VII REGION                   4     18000000
1                          SEREMI IV REGION                  14     16877588
3                     SEREMI MINVU I REGION                   7     12696744
2                          SEREMI IX REGION                   1      9750000
13                  SEREMI ÑUBLE-REGIÓN XVI                   2      6000000
15                  Seremi-Minvu XII Región                   6      5679222

In [5]:
resumen_tipo_compra = df.groupby("Tipo compra").agg(
    Cantidad_Registros=("ID Proyecto", "count"),
    Monto_Total=("Monto Total Ítem Año 2025", "sum")
).reset_index()

resumen_tipo_compra = resumen_tipo_compra.sort_values(
    "Monto_Total",
    ascending=False
)

resumen_tipo_compra

   Tipo compra  Cantidad_Registros  Monto_Total
5            6                 486  67870307246
4            5                  79   7440038312
0            1                 159   4921854535
3            4                  83   3921795608
1            2                   4    123733890
2            3                  20     56552759