In [1]:
import pandas as pd

In [4]:
df = pd.read_excel("plan_de_compras_2025.xlsx")
df.head()

,Unidad de Compra,ID Proyecto,Tipo Proyecto,Estado Proyecto,Código presupuestario,Nombre Proyecto,Descripción Proyecto,Cantidad de Ítems,Nombre ítem,Tipo compra,...,Cargo responsable,Teléfono responsable,Correo responsable,Fecha de Inicio Compra,Fecha Publicación PAC 2025,Cantidad OC Asociadas Ítem 2025,OC Asociada Item 2025,Item De Arraste,Monto De Arrastre,Meses envio OC de Arraste
0,Ministerio de Vivienda y Urbanismo(766),587-259-PC22,Proyecto estratégico,Publicado,2207-2209-33,Servicio arriendo de una plataforma de gestión...,Servicio de arriendo de una plataforma de gest...,2,Servicio arriendo de una plataforma de gestión...,1,...,Coordinadora de Tecnologías Informáticas | Sis...,2 -2901 1198-,mzunigas@minvu.cl,2022-11-01,2022-11-08,0,NaN,1,20000000,2025-01-01
1,SEREMI MINVU V REGION,632-28-PC22,Proyecto operacional,Publicado,2206-2206001,Servicio de Mantención y Reparaciones Menores ...,Convenio de Suministro para el Servicio de Man...,1,Mantenimiento y Reparación de Edificaciones,1,...,Encargado Sección Administración y Finanzas,32-2186802-,agardaix@minvu.cl,2022-02-01,2022-11-08,1,632-7-SE22,1,4500000,2025-01-01
2,SEREMI MINVU V REGION,632-32-PC22,Proyecto operacional,Publicado,2204001,Servicios de Impresión-Seremi Valparaiso,Servicios de Impresión de Materiales SEREMI y ...,1,Materiales de Oficina,1,...,Encargado Sección Administración y Finanzas,32-2186802-,agardaix@minvu.cl,2022-08-01,2022-11-08,0,NaN,1,3825000,2025-01-01
3,SEREMI MINVU V REGION,632-34-PC22,Proyecto operacional,Publicado,2209006,Servicio de Arriendo de Impresoras Multifuncio...,Servicio de Arriendo de Impresoras Multifuncio...,2,Arriendo de Equipos Informáticos,1,...,Encargado Sección Administración y Finanzas,32-2186802-,agardaix@minvu.cl,2022-08-01,2022-11-08,1,632-13-CC23,1,4500000,2025-01-01
4,SEREMI MINVU V REGION,632-41-PC22,Proyecto operacional,Publicado,2205005,Servicio de Telefonía Fija-Seremi Valparaiso,Servicio de Telefonía Fija SEREMI,2,Telefonía Fija,1,...,Encargado Sección Administración y Finanzas,322186802,agardaix@minvu.cl,2022-12-01,2022-11-08,0,NaN,1,26400000,2025-01-01

In [8]:
# Extraer los últimos 2 dígitos del código de proyecto (el año)

df["Año Proyecto"] = df["ID Proyecto"].astype(str).str[-2:]

 

# Filtrar solo los proyectos del año 2025 (código termina en "25")

df_2025 = df[df["Año Proyecto"] == "25"]

 

print(f"Total de registros: {len(df)}")

print(f"Registros año 2025: {len(df_2025)}")

 

df_2025.head(20)

Total de registros: 831
Registros año 2025: 648

,Unidad de Compra,ID Proyecto,Tipo Proyecto,Estado Proyecto,Código presupuestario,Nombre Proyecto,Descripción Proyecto,Cantidad de Ítems,Nombre ítem,Tipo compra,...,Teléfono responsable,Correo responsable,Fecha de Inicio Compra,Fecha Publicación PAC 2025,Cantidad OC Asociadas Ítem 2025,OC Asociada Item 2025,Item De Arraste,Monto De Arrastre,Meses envio OC de Arraste,Año Proyecto
183,Ministerio de Vivienda y Urbanismo(766),1583-4-PC25,Proyecto operacional,Actualizado,2204007,INSUMOS PARA DISPENSADORES - ADMINISTRACIÓN DE...,"TOALLA DE PAPEL PREMIUM DOBLE HOJA , PAPEL HIG...",1,INSUMOS PARA DISPENSADORES-3 - ADMINISTRACIÓN ...,5,...,02-29011170-,pcarcenac@minvu.cl,2025-01-01,2025-11-27,3,587-583-CM25,0,0,NaT,25
184,Ministerio de Vivienda y Urbanismo(766),1583-4-PC25,Proyecto operacional,Actualizado,2204007,INSUMOS PARA DISPENSADORES - ADMINISTRACIÓN DE...,"TOALLA DE PAPEL PREMIUM DOBLE HOJA , PAPEL HIG...",1,INSUMOS PARA DISPENSADORES-3 - ADMINISTRACIÓN ...,5,...,02-29011170-,pcarcenac@minvu.cl,2025-01-01,2025-11-27,3,587-236-CM25,0,0,NaT,25
185,Ministerio de Vivienda y Urbanismo(766),1583-4-PC25,Proyecto operacional,Actualizado,2204007,INSUMOS PARA DISPENSADORES - ADMINISTRACIÓN DE...,"TOALLA DE PAPEL PREMIUM DOBLE HOJA , PAPEL HIG...",1,INSUMOS PARA DISPENSADORES-3 - ADMINISTRACIÓN ...,5,...,02-29011170-,pcarcenac@minvu.cl,2025-01-01,2025-11-27,3,587-52-AG25,0,0,NaT,25
186,Ministerio de Vivienda y Urbanismo(766),1583-5-PC25,Proyecto operacional,Actualizado,2204010,MATERIAL DE ASEO-1-ADMINISTRACIÓN DE INSUMOS,JABÓN ESPUMA PARA USO GENERAL,1,MATERIAL DE ASEO-1 - ADMINISTRACIÓN DE INSUMOS,5,...,29-011170-,pcarcenac@minvu.cl,2025-02-01,2025-11-27,4,658-98-AG25,0,0,NaT,25
187,Ministerio de Vivienda y Urbanismo(766),1583-5-PC25,Proyecto operacional,Actualizado,2204010,MATERIAL DE ASEO-1-ADMINISTRACIÓN DE INSUMOS,JABÓN ESPUMA PARA USO GENERAL,1,MATERIAL DE ASEO-1 - ADMINISTRACIÓN DE INSUMOS,5,...,29-011170-,pcarcenac@minvu.cl,2025-02-01,2025-11-27,4,587-530-CM25,0,0,NaT,25
188,Ministerio de Vivienda y Urbanismo(766),1583-5-PC25,Proyecto operacional,Actualizado,2204010,MATERIAL DE ASEO-1-ADMINISTRACIÓN DE INSUMOS,JABÓN ESPUMA PARA USO GENERAL,1,MATERIAL DE ASEO-1 - ADMINISTRACIÓN DE INSUMOS,5,...,29-011170-,pcarcenac@minvu.cl,2025-02-01,2025-11-27,4,587-34-CM25,0,0,NaT,25
189,Ministerio de Vivienda y Urbanismo(766),1583-5-PC25,Proyecto operacional,Actualizado,2204010,MATERIAL DE ASEO-1-ADMINISTRACIÓN DE INSUMOS,JABÓN ESPUMA PARA USO GENERAL,1,MATERIAL DE ASEO-1 - ADMINISTRACIÓN DE INSUMOS,5,...,29-011170-,pcarcenac@minvu.cl,2025-02-01,2025-11-27,4,658-93-AG25,0,0,NaT,25
190,Ministerio de Vivienda y Urbanismo(766),1583-6-PC25,Proyecto operacional,Actualizado,2204007,MATERIAL DE ASEO-2 - ADMINISTRACIÓN DE INSUMOS,Insumos de aseo para stock de bodega y entrega...,1,MATERIAL DE ASEO-2 - ADMINISTRACIÓN DE INSUMOS,5,...,29-011170-,pcarcenac@minvu.cl,2025-02-01,2025-11-27,1,587-60-AG25,0,0,NaT,25
191,Ministerio de Vivienda y Urbanismo(766),1583-8-PC25,Proyecto operacional,Actualizado,2204007,MATERIAL DE ESCRITORIO-1 - ADMINISTRACIÓN DE I...,Material destinado a las diferentes dependenci...,1,MATERIAL DE ESCRITORIO-1 - ADMINISTRACIÓN DE I...,6,...,29-011170-,pcarcenac@minvu.cl,2025-02-01,2025-11-27,4,587-44-CM25,0,0,NaT,25
192,Ministerio de Vivienda y Urbanismo(766),1583-8-PC25,Proyecto operacional,Actualizado,2204007,MATERIAL DE ESCRITORIO-1 - ADMINISTRACIÓN DE I...,Material destinado a las diferentes dependenci...,1,MATERIAL DE ESCRITORIO-1 - ADMINISTRACIÓN DE I...,6,...,29-011170-,pcarcenac@minvu.cl,2025-02-01,2025-11-27,4,587-526-CM25,0,0,NaT,25
193,Ministerio de Vivienda y Urbanismo(766),1583-8-PC25,Proyecto operacional,Actualizado,2204007,MATERIAL DE ESCRITORIO-1 - ADMINISTRACIÓN DE I...,Material destinado a las diferentes dependenci...,1,MATERIAL DE ESCRITORIO-1 - ADMINISTRACIÓN DE I...,6,...,29-011170-,pcarcenac@minvu.cl,2025-02-01,2025-11-27,4,587-527-CM25,0,0,NaT,25
194,Ministerio de Vivienda y Urbanismo(766),1583-8-PC25,Proyecto operacional,Actualizado,2204007,MATERIAL DE ESCRITORIO-1 - ADMINISTRACIÓN DE I...,Material destinado a las diferentes dependenci...,1,MATERIAL DE ESCRITORIO-1 - ADMINISTRACIÓN DE I...,6,...,29-011170-,pcarcenac@minvu.cl,2025-02-01,2025-11-27,4,587-43-CM25,0,0,NaT,25
195,Ministerio de Vivienda y Urbanismo(766),1583-9-PC25,Proyecto operacional,Actualizado,2204001,MATERIAL DE ESCRITORIO-2 - ADMINISTRACION DE I...,Material destinado a las diferentes dependenci...,1,MATERIAL DE ESCRITORIO-2 - ADMINISTRACIÓN DE I...,5,...,29-011170-,pcarcenac@minvu.cl,2025-01-01,2025-11-27,3,587-101-AG25,0,0,NaT,25
196,Ministerio de Vivienda y Urbanismo(766),1583-9-PC25,Proyecto operacional,Actualizado,2204001,MATERIAL DE ESCRITORIO-2 - ADMINISTRACION DE I...,Material destinado a las diferentes dependenci...,1,MATERIAL DE ESCRITORIO-2 - ADMINISTRACIÓN DE I...,5,...,29-011170-,pcarcenac@minvu.cl,2025-01-01,2025-11-27,3,587-243-AG25,0,0,NaT,25
197,Ministerio de Vivienda y Urbanismo(766),1583-9-PC25,Proyecto operacional,Actualizado,2204001,MATERIAL DE ESCRITORIO-2 - ADMINISTRACION DE I...,Material destinado a las diferentes dependenci...,1,MATERIAL DE ESCRITORIO-2 - ADMINISTRACIÓN DE I...,5,...,29-011170-,pcarcenac@minvu.cl,2025-01-01,2025-11-27,3,587-98-AG25,0,0,NaT,25
198,Ministerio de Vivienda y Urbanismo(766),1583-10-PC25,Proyecto operacional,Actualizado,2202001,TARJETAS DE VESTUARIO-1 - ADMINISTRACION DE IN...,TARJETAS VESTUARIO SECRETARIAS,1,TARJETAS DE VESTUARIO-1 - ADMINISTRACIÓN DE IN...,5,...,29-011170-,pcarcenac@minvu.cl,2025-03-01,2025-11-27,2,587-211-CM25,0,0,NaT,25
199,Ministerio de Vivienda y Urbanismo(766),1583-10-PC25,Proyecto operacional,Actualizado,2202001,TARJETAS DE VESTUARIO-1 - ADMINISTRACION DE IN...,TARJETAS VESTUARIO SECRETARIAS,1,TARJETAS DE VESTUARIO-1 - ADMINISTRACIÓN DE IN...,5,...,29-011170-,pcarcenac@minvu.cl,2025-03-01,2025-11-27,2,587-204-CM25,0,0,NaT,25
200,Ministerio de Vivienda y Urbanismo(766),1583-11-PC25,Proyecto operacional,Actualizado,2202001,TARJETAS DE VESTUARIO-2 - ADMINISTRACION DE IN...,TARJETAS VESTUARIO SECRETARIOS,1,TARJETAS DE VESTUARIO-2 - ADMINISTRACIÓN DE IN...,5,...,29-011170-,pcarcenac@minvu.cl,2025-03-01,2025-11-27,1,587-205-CM25,0,0,NaT,25
201,Ministerio de Vivienda y Urbanismo(766),1583-12-PC25,Proyecto operacional,Actualizado,2202001,TARJETAS DE VESTUARIO-3 - ADMINISTRACION DE IN...,TARJETAS VESTUARIO AUXILIARES-CONDUCTORES-BODE...,1,TARJETAS DE VESTUARIO-3 - ADMINISTRACIÓN DE IN...,5,...,29-011170-,pcarcenac@minvu.cl,2025-03-01,2025-11-27,1,587-203-CM25,0,0,NaT,25
202,Ministerio de Vivienda y Urbanismo(766),1583-13-PC25,Proyecto operacional,Actualizado,2202001,TARJETAS DE VESTUARIO-4 - ADMINISTRACION DE IN...,TARJETAS VESTUARIO OFICIAL DE PARTES,1,TARJETAS DE VESTUARIO-4 - ADMINISTRACIÓN DE IN...,5,...,29-011170-,pcarcenac@minvu.cl,2025-03-01,2025-11-27,3,587-252-CM25,0,0,NaT,25

In [7]:
print(df["ID Proyecto"].astype(str).str[-4:].value_counts().loc["PC25"])

# Crea la tabla de conteos

tabla_conteo = df["ID Proyecto"].astype(str).str[-4:].value_counts().to_frame()

# Muestra únicamente la fila de PC25

tabla_conteo.loc[["PC25"]]

648

             count
ID Proyecto
PC25           648